package com.vhms.vhms.model;

public enum NotificationType {
    APPOINTMENT_REQUESTED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_ASSIGNED,
    INVOICE_GENERATED,
    PAYMENT_REMINDER,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED
}
