spring.application.name=vhms

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://natasharuth255_db_user:e0JVGUyszyzkiPny@ruth.tmhfj1q.mongodb.net/VHMS?retryWrites=true&w=majority&appName=Ruth
spring.data.mongodb.database=VHMS

# Server
server.port=8080
