spring.application.name=vhms

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/vhms_db?retryWrites=true&w=majority
spring.data.mongodb.database=vhms_db

# Server
server.port=8080
